# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pods-x-remoteCache' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'AcknowList'
	pod 'AdGeneration'
	pod 'Alamofire'
	pod 'AppsFlyerFramework'
	pod 'Compass'
	pod 'Crashlytics'
	pod 'Fabric'
	pod 'Firebase'
	pod 'Firebase/AdMob'
	pod 'Firebase/Auth'
	pod 'Firebase/DynamicLinks'
	pod 'Firebase/Messaging'
	pod 'Firebase/RemoteConfig'
	pod 'GoogleAnalytics'
	pod 'GoogleIDFASupport'
	pod 'GoogleTagManager'
	pod 'RealmSwift'
	pod 'RxSwift'
	pod 'SDWebImage'
	pod 'SwiftyUserDefaults'
	pod 'Unbox'
	pod 'BonMot'
	pod 'Crashlytics'
	pod 'IQKeyboardManagerSwift'
	pod 'Nuke'
	pod 'Nuke-Alamofire-Plugin'
	pod 'OneSignal'
	pod 'p2.OAuth2'
	pod 'Reusable'
	pod 'SnapKit'
	pod 'LocalizableCheck'
	pod 'Sourcery'
	pod 'SwiftGen'
	pod 'SwiftLint'
	pod 'TagListView'
	pod 'SearchTextField'
	pod 'SwiftMessages'
	pod 'Tabman'
	pod 'Koloda'
end
